# Filled in by the GUI
#iso-filename: <FILLME your ISO filename>
#output-video-filename: <FILLME your video filename here>
#chadsoft-ghost-page: <FILLME your link here>
#track-name: <FILLME your track name>

# Keep these as is
ffmpeg-filename: bin/ffmpeg.exe
ffprobe-filename: bin/ffprobe.exe

timeline: mkchannel
speedometer: fancy
speedometer-metric: engine
speedometer-decimal-places: 1
input-display: gcn
music-filename: bgm
hq-textures: true
top-10-location: ww
mk-channel-ghost-description: Ghost Data
encode-type: crf
video-codec: libx264
audio-codec: libopus
crf-value: 15
youtube-settings: true
keep-window: true

chadsoft-read-cache: false
chadsoft-write-cache: false
encode-only: false
input-display-dont-create: false
dolphin-resolution: 480p
h26x-preset: slow
game-volume: 1.0
music-volume: 1.0
output-width: null
unbuffered-output: true
ending-message: "Video recorded by https://bit.ly/AutoTTRecorderGUI"
